import Ads2 from "./components/ads/ads-2/ads-2";
import LoadingProgressBar from "./components/common/LoadingProgressBar";
import Footer from "./components/footer/footer";
import Navbar from "./components/navbar/navbar";
import "./globals.css";

export const metadata = {
  title: "محصولات لومیت | ارزان‌ترین فروشنده را پیدا کن",
  description: "Generated by create next app",
  icons: {
    icon: "/img/favicon-1.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
          rel="stylesheet"
        />
        <link
          href="https://cdn.boxicons.com/fonts/basic/boxicons.min.css"
          rel="stylesheet"
        />
      </head>
      <body className="dark">
        <LoadingProgressBar />
        {children}
      </body>
    </html>
  );
}
